// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: 'AIzaSyDpbgyiNeeK264AJiE9RRUy-4jtq76oDtk',
  appId: '1:621500092009:web:1dcc8581c41f11c2e99cf8',
  messagingSenderId: '621500092009',
  projectId: 'findex-f8723',
  authDomain: 'findex-f8723.firebaseapp.com',
  storageBucket: 'findex-f8723.firebasestorage.app',
  measurementId: 'G-PGG8E9SJ6C',
  databaseURL: 'https://findex-f8723-default-rtdb.firebaseio.com', // ← ADD THIS
);

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTc-ItZD9BeGJ0Ow9ECaR4jANDTRs5zu0',
    appId: '1:621500092009:android:1b9bced1f8cb3d2de99cf8',
    messagingSenderId: '621500092009',
    projectId: 'findex-f8723',
    storageBucket: 'findex-f8723.firebasestorage.app',
    databaseURL: 'https://findex-f8723-default-rtdb.firebaseio.com', 
  );
}
